services:
  PrestaShop\Module\PrestashopFacebook\Factory\GoogleCategoryEssentialsApiClientFactory:
    class: PrestaShop\Module\PrestashopFacebook\Factory\GoogleCategoryEssentialsApiClientFactory

  PrestaShop\Module\PrestashopFacebook\Factory\FacebookEssentialsApiClientFactory:
    class: PrestaShop\Module\PrestashopFacebook\Factory\FacebookEssentialsApiClientFactory
