name: Module Facebook CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened,edited,reopened,synchronize,labeled]

env:
  MODULE_NAME: ps_facebook
  GCLOUD_TOKEN_PATH: ./token.json
  PS_IMG_VERSION: prestashop/prestashop:1.7.6.9-7.2-apache

jobs:

  build_push_inte:
    name: CI/CD integration ps_facebook
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: contains(github.event.pull_request.labels.*.name, 'quality assurance needed') || github.ref == 'refs/heads/dev'

    steps:
      # Fixed babel build : https://github.com/ember-cli/ember-cli/issues/9235#issuecomment-635254959
      - name: Use Node.js 12.16.3
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.3

      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_INTEGRATION }}
          service_account_key: ${{ secrets.G_CREDENTIAL_INTEGRATION }}
          export_default_credentials: true

      - name: Copy env files
        run: |
          gcloud components install beta
          gcloud beta secrets versions access latest --secret="facebook-module" > .env
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.G_CREDENTIAL_INTEGRATION }}

      - name: Build JS dependencies
        uses: PrestaShopCorp/github-action-build-js/12@v1.0
        with:
          cmd: npm
          path: ./_dev

      - name: Install composer dependencies
        run: composer install --no-dev -o

      - name: Clean-up project
        uses: PrestaShopCorp/github-action-clean-before-deploy@v1.0

      - name: Copy modules
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_INTEGRATION }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: ps_facebook

      - name: Delete old modules 1.7
        continue-on-error: true
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_INTEGRATION }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo su -c 'docker exec $(docker ps -q -f "ancestor=${{ env.PS_IMG_VERSION }}" -f "name=facebook") rm -rf modules/ps_facebook'

      - name: Move modules
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_INTEGRATION }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo su -c 'cp -R ps_facebook ${{ secrets.MODULE_PATH }}/ps_facebook'
            sudo su -c 'chown -R www-data:www-data ${{ secrets.MODULE_PATH }}/ps_facebook'

      - name: Install modules
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_INTEGRATION }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo su -c 'docker exec $(docker ps -q -f "ancestor=${{ env.PS_IMG_VERSION }}" -f "name=facebook") bin/console prestashop:module uninstall ps_facebook || true'
            sudo su -c 'docker exec $(docker ps -q -f "ancestor=${{ env.PS_IMG_VERSION }}" -f "name=facebook") bin/console prestashop:module install ps_facebook'

      - name: Clear cache
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_INTEGRATION }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo su -c 'docker exec $(docker ps -q -f "ancestor=${{ env.PS_IMG_VERSION }}" -f "name=facebook") bin/console cache:cl'
            sudo su -c 'docker exec $(docker ps -q -f "ancestor=${{ env.PS_IMG_VERSION }}" -f "name=facebook") chmod -R 777 var/cache var/logs'

      - name: Delete tmp module
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_INTEGRATION }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: rm -rf ps_facebook
